#!/usr/bin/env python3
"""Pipe-level regression for dsv4_run --serve.

Usage: python tests/test_serve_protocol.py RUNNER TINY.gguf [timeout-seconds]
The tiny GGUF is generated by tools/tiny_model.py; no model download or GPU is needed.
"""
import queue
import subprocess
import sys
import threading
import time


def fail(message, proc, seen):
    tail = "\n".join(seen[-20:])
    raise RuntimeError(f"{message}\nrecent stdout:\n{tail}\nexit={proc.poll()}")


def main():
    if len(sys.argv) not in (3, 4):
        print(__doc__.strip(), file=sys.stderr)
        return 2
    runner, model = sys.argv[1:3]
    timeout = float(sys.argv[3]) if len(sys.argv) == 4 else 30.0
    proc = subprocess.Popen(
        [runner, "--model", model, "--cpu", "--serve", "--ctx", "64", "--threads", "2"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        bufsize=0,
    )
    lines = queue.Queue()
    seen = []

    def read_stdout():
        try:
            for raw in proc.stdout:
                lines.put(raw.decode("utf-8", "replace").rstrip("\r\n"))
        finally:
            lines.put(None)

    threading.Thread(target=read_stdout, daemon=True).start()

    def next_line(deadline):
        left = deadline - time.monotonic()
        if left <= 0:
            fail("timed out waiting for protocol output", proc, seen)
        try:
            line = lines.get(timeout=left)
        except queue.Empty:
            fail("timed out waiting for protocol output", proc, seen)
        if line is None:
            fail("runner closed stdout unexpectedly", proc, seen)
        seen.append(line)
        return line

    def until(predicate, deadline, description):
        while True:
            line = next_line(deadline)
            if predicate(line):
                return line
            if line.startswith("ERR "):
                fail(f"runner rejected request while waiting for {description}", proc, seen)

    def send(data):
        proc.stdin.write(data)
        proc.stdin.flush()

    deadline = time.monotonic() + timeout
    try:
        ready = until(lambda s: s.startswith("READY "), deadline, "READY")
        if ready != "READY 64 stop":
            fail(f"unexpected READY line: {ready}", proc, seen)

        # First prove a normal complete request returns PP, one token, and DONE.
        send(b"GEN 1 temperature=0 seed=7 1\n")
        until(lambda s: s.startswith("PP "), deadline, "first PP")
        until(lambda s: s.startswith("T "), deadline, "first generated token")
        done = until(lambda s: s.startswith("DONE "), deadline, "first DONE")
        if done.split()[-1] not in ("stop", "length"):
            fail(f"unexpected completion of normal request: {done}", proc, seen)

        # Use a long prompt so there is a clear gap between progress reports.
        # Send STOP without LF immediately after GEN; reaching multiple PP
        # reports proves the reader doesn't wait for the rest of that line.
        long_prompt = ",".join(["2"] * 63)
        send(f"GEN 1 temperature=0 seed=3 {long_prompt}\n".encode("ascii"))
        send(b"STOP")
        first_progress = until(lambda s: s.startswith("PP ") and s.split()[2] == "63", deadline, "second PP")
        if first_progress.split()[1] != "8":
            fail(f"expected first chunk progress at 8 prompt tokens, got: {first_progress}", proc, seen)
        later_progress = until(
            lambda s: s.startswith("PP ") and s.split()[2] == "63" and int(s.split()[1]) > 8,
            deadline,
            "progress after partial STOP",
        )
        if int(later_progress.split()[1]) <= 8:
            fail(f"prompt did not advance after partial STOP: {later_progress}", proc, seen)
        send(b"\n")
        cancelled = until(lambda s: s.startswith("DONE "), deadline, "cancelled DONE")
        if cancelled.split()[-1] != "cancel":
            fail(f"partial STOP did not cancel the request: {cancelled}", proc, seen)

        # Cancellation must leave the protocol loop ready for another request.
        send(b"GEN 1 temperature=0 seed=11 3\n")
        until(lambda s: s.startswith("PP "), deadline, "third PP")
        until(lambda s: s.startswith("T "), deadline, "third generated token")
        final_done = until(lambda s: s.startswith("DONE "), deadline, "third DONE")
        if final_done.split()[-1] not in ("stop", "length"):
            fail(f"unexpected completion after cancellation: {final_done}", proc, seen)

        send(b"QUIT\n")
        proc.stdin.close()
        remaining = max(0.0, deadline - time.monotonic())
        proc.wait(timeout=remaining)
        if proc.returncode != 0:
            fail("runner exited with a failure status", proc, seen)
        print("serve protocol passed: READY, complete GEN, partial STOP without newline, continued progress, cancellation, next GEN, QUIT")
        return 0
    except Exception:
        if proc.poll() is None:
            proc.kill()
            proc.wait()
        raise
    finally:
        if proc.poll() is None:
            proc.kill()
            proc.wait()


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, subprocess.TimeoutExpired) as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
